module.exports.foods = [{
    name: "Strawberry",
    tags: ["Fruits"]
}, {
    name: "Blueberry",
    tags: ["Fruits"]
}, {
    name: "Raspberry",
    tags: ["Fruits"]
}, {
    name: "Orange",
    tags: ["Fruits"]
}, {
    name: "Kumquat",
    tags: ["Fruits"]
}, {
    name: "Grapefruit",
    tags: ["Fruits"]
}, {
    name: "Plum",
    tags: ["Fruits"]
}, {
    name: "Cherry",
    tags: ["Fruits"]
}, {
    name: "Carrot",
    tags: ["Roots"]
}, {
    name: "Onion",
    tags: ["Roots"]
}, {
    name: "Ginger",
    tags: ["Roots"]
}, {
    name: "Beet",
    tags: ["Roots"]
}, {
    name: "Rutabega",
    tags: ["Roots"]
}, {
    name: "Potato",
    tags: ["Roots"]
}, {
    name: "Yuca",
    tags: ["Roots"]
}, {
    name: "Fennel",
    tags: ["Roots", "Stalks"]
}, {
    name: "Celery",
    tags: ["Stalks"]
}, {
    name: "Asparagus",
    tags: ["Stalks"]
}, {
    name: "Spinach",
    tags: ["Leaves"]
}, {
    name: "Kale",
    tags: ["Leaves"]
}, {
    name: "Cilantro",
    tags: ["Leaves"]
}, {
    name: "Chard",
    tags: ["Leaves"]
}, {
    name: "Bok Choi",
    tags: ["Leaves"]
}, {
    name: "Basil",
    tags: ["Leaves"]
}];
